### ISSUE TITLE
Error in cmake

### ISSUE THREAD

**Issue by jeffreyzhu604** [milq/milq#1]
Hello, I am running into errors when I enter the following command:

cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON ..

-- checking for module 'gstreamer-base-1.0'
--   package 'gstreamer-base-1.0' not found
-- checking for module 'gstreamer-video-1.0'
--   package 'gstreamer-video-1.0' not found
-- checking for module 'gstreamer-app-1.0'
--   package 'gstreamer-app-1.0' not found
-- checking for module 'gstreamer-riff-1.0'
--   package 'gstreamer-riff-1.0' not found
-- checking for module 'gstreamer-pbutils-1.0'
--   package 'gstreamer-pbutils-1.0' not found
-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - not found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- checking for module 'libgphoto2'
--   package 'libgphoto2' not found
-- checking for module 'tbb'
--   package 'tbb' not found

and also,

-- VTK support is disabled. Incompatible combination: OpenCV + Qt5 and VTK ver.6.1.0 + Qt4

I tried Google'ing everything and can't seem to find a solution to my problem. I am running the NOOBS OS on the raspberry pi.

**Comment by milq** [comment]
_jeffreyzhu604_, thank you for your comment.

The script `install-opencv.sh` is for Debian and Ubuntu.

In a future, it could be possible that I fork this script and adapt it to Raspberry Pi and with Raspbian OS.

Kind regards,

Nacho.
