### ISSUE TITLE
BUGFIX stdlib.h

### ISSUE THREAD

**Issue by MEmx** [milq/milq#10]
"fatal error: stdlib.h: No such file or directory" due to wrong assignments can be avoided by adding

-DENABLE_PRECOMPILED_HEADERS=OFF

in cmake.

**Comment by milq** [comment]
@MEmx 

Which OS are you using? Thanks in advance.

**Comment by scruff2** [comment]
I had the same issue and resolution, when running Linux Ubuntu 16.10.
This is a known issue and has also been addressed here:
http://stackoverflow.com/questions/40262928/error-compiling-opencv-fatal-error-stdlib-h-no-such-file-or-directory
