### ISSUE TITLE
fatal error: stdlib.h: No such file or directory (on Ubuntu 17.04)

### ISSUE THREAD

**Issue by mspoorendonk** [milq/milq#17]
I had to add DENABLE_PRECOMPILED_HEADERS=OFF to the cmake line on Ubuntu 17.04 as mentioned here: https://stackoverflow.com/questions/40262928/error-compiling-opencv-fatal-error-stdlib-h-no-such-file-or-directory

`cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON -DENABLE_PRECOMPILED_HEADERS=OFF ..`

**Comment by milq** [comment]
Script updated, thanks!
