### ISSUE TITLE
Code tested

### ISSUE THREAD

**Issue by lucasamparo** [milq/milq#24]
Code tested and still working with 3.3.0 version.

Only need to install Qt5
sudo apt install qtbase5-dev

and i change to put the version in a variable
`sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get -y autoremove

sudo apt-get install -y build-essential cmake

sudo apt-get install -y qt5-default libvtk6-dev
sudo apt install qtbase5-dev

sudo apt-get install -y zlib1g-dev libjpeg-dev libwebp-dev libpng-dev libtiff5-dev libjasper-dev libopenexr-dev libgdal-dev

sudo apt-get install -y libdc1394-22-dev libavcodec-dev libavformat-dev libswscale-dev libtheora-dev libvorbis-dev libxvidcore-dev libx264-dev yasm libopencore-amrnb-dev libopencore-amrwb-dev libv4l-dev libxine2-dev

sudo apt-get install -y libtbb-dev libeigen3-dev

sudo apt-get install -y doxygen

version = "3.3.0"
sudo apt-get install -y unzip wget
wget https://github.com/opencv/opencv/archive/$version.zip
unzip $version.zip
rm $version.zip
mv opencv-$version OpenCV
cd OpenCV
mkdir build
cd build
cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON -DWITH_XINE=ON -DBUILD_EXAMPLES=ON -DENABLE_PRECOMPILED_HEADERS=OFF ..
make -j $(nproc)
sudo make install
sudo ldconfig

**Comment by milq** [comment]
Thanks.
