### ISSUE TITLE
trying to install opencv contrib in raspberry pi 3

### ISSUE THREAD

**Issue by vatzmehta** [milq/milq#30]
ry
 #include_next <stdlib.h>
                         ^
compilation terminated.
modules/core/CMakeFiles/pch_Generate_opencv_core.dir/build.make:62: recipe for target 'modules/core/precomp.hpp.gch/opencv_core_RELEASE.gch' failed
make[2]: *** [modules/core/precomp.hpp.gch/opencv_core_RELEASE.gch] Error 1
CMakeFiles/Makefile2:2014: recipe for target 'modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all' failed
make[1]: *** [modules/core/CMakeFiles/pch_Generate_opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by vatzmehta** [comment]
https://github.com/opencv/opencv_contrib
trying from this source and getting the above error

**Comment by milq** [comment]
@vatzmehta Sorry, my script is only work on Debian and Ubuntu. Thanks.
