### ISSUE TITLE
Contrib installation

### ISSUE THREAD

**Issue by DaniloRodrigo** [milq/milq#39]
Hi, how can I add the contrib to this installation?

**Comment by nelkabosal** [comment]
I had the same question (I'm assuming you're talking about including OpenCV contrib to be able to use SIFT/SURF/etc.). I had to combine advice from https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/ and from this repository. I'm not confident in the quality of my solution, as I think there's a handful of settings and dependencies that differ between their methods of installation, but you at least will want to do something like
````
wget -O opencv_contrib.zip https://github.com/Itseez/opencv_contrib/archive/${OPENCV_VERSION}.zip
unzip opencv_contrib.zip
````
And include 
`-DOPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-${OPENCV_VERSION}/modules`
in the cmake line.

For it to work for me personally, I also removed the `mv opencv-${OPENCV_VERSION} OpenCV` line and used `wget -O opencv.zip https://github.com/Itseez/opencv/archive/${OPENCV_VERSION}.zip` for the main OpenCV files. Additionally, I just used the cmake line from https://www.pyimagesearch.com/2016/10/24/ubuntu-16-04-how-to-install-opencv/ 
I didn't use the virtual environment as discussed in the link. There is some risk with that.
I wouldn't suggest blindly following my suggestions, as I'm just a novice, but feel free to build off them as you see fit.

**Comment by milq** [comment]
@DaniloRodrigo, @nelkabosal, currently I'm working in the script and one of the changes is adding the 'contrib' installation.

Thank you for your support.

**Comment by All4Gis** [comment]
Amazing script.
I'm making a small change for install OpenCV Contrib.I don't do a PR because I don't know how you want to integrate it into the script.

```
rm -rf OpenCV

sudo apt-get install -y unzip wget
wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip
unzip ${OPENCV_VERSION}.zip && rm ${OPENCV_VERSION}.zip

wget https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip
unzip ${OPENCV_VERSION}.zip && rm ${OPENCV_VERSION}.zip

mv opencv-${OPENCV_VERSION} OpenCV
mv opencv_contrib-${OPENCV_VERSION} opencv_contrib
mv opencv_contrib/ OpenCV/

cd OpenCV && mkdir build && cd build
cmake -DWITH_QT=ON -DWITH_OPENGL=ON -DBUILD_opencv_dnn=ON -DFORCE_VTK=ON -DWITH_TBB=ON -DWITH_GDAL=ON \
      -DWITH_XINE=ON -DBUILD_EXAMPLES=ON -DENABLE_PRECOMPILED_HEADERS=OFF \
      -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ..
make -j8
sudo make install
sudo ldconfig
```

**Comment by milq** [comment]
Thank you for your contributions @nelkabosal and @All4Gis.

Now, I commit the new version of the script with OpenCV Contrib installation.

I appreciate your effort enormously.

Thanks again.
