### ISSUE TITLE
Upgrading system

### ISSUE THREAD

**Issue by MichalJuranek** [milq/milq#43]
Hello, 
unfortunately, I ran your script without realizing that it will upgrade my system, could you please put a warning or add the option of asking the user if they want to upgrade their system. 
Thank you,

**Comment by simo996** [comment]
Thank you for pointing out this issue, 
Today I'm graduating so I won't be able to modify the instructions but I promise I will do it. 
Let me know if I can help you furtherway 

Have a good day
Thank you for your help 

Il giorno 25 ott 2018, 09:06, alle ore 09:06, MichalJuranek <notifications@github.com> ha scritto:

**Comment by milq** [comment]
@MichalJuranek, now the script only does APT updates, not upgrades.

Thanks.
