### ISSUE TITLE
You can easily kill systems with your installer !

### ISSUE THREAD

**Issue by kimjohans** [milq/milq#44]
Please remove (!!) the following lines from your setup:

sudo apt-get -y upgrade
sudo apt-get -y dist-upgrade
sudo apt-get -y autoremove

... or at least remove the "-y" part from those commands.

Those type of "setups" will kill systems of users because other software is not prepared for the next linux version or configurations will be changed. Unprofessional setups like yours are the reason, why users ALWAYS have to check and read those scripts.

The minimum should be an explicit warning about those risks after the script execution.

**Comment by milq** [comment]
@kimjohans, you're absolutely right. I'll comment these lines. Thank you.
