### ISSUE TITLE
Linking to OpenCV library using Ubuntu and Eclipse 

### ISSUE THREAD

**Issue by JulyJim** [milq/milq#5]
I hope this is the right place to ask this , if not,  just ignore it.
I have managed to execute one of he scripts  - install-opencv.sh - 
and have some issues with results. 
First I like to know why the "lib"  ends up in usr/local/lib , but that is not that important. 
When I try to add library path into Eclipse linker   (_L) option  I get three directories Python x and a ton of grayed out .so files which I cannot access. 
Even when I select one of the Python's directories for a path (_L)  I cannot add any real library (-l) .

**Comment by dinujohnk** [comment]
try installing each code by code instead of running the script
