### ISSUE TITLE
install-opencv.sh missing step to cd into opencv folder

### ISSUE THREAD

**Issue by jomoengineer** [milq/milq#55]
In the install-opencv.sh script, at line 82, shouldn't there be a step to cd into '**opencv-${OPENCV_VERSION}**' before creating the build folder?  As written it appears it will just go into OpenCV and create the build folder but there is no CMakeLists.txt under OpenCV from the steps shown.  It would be under '**OpenCV/opencv-${OPENCV_VERSION}**' instead.

**Comment by milq** [comment]
The script does the following:
```
wget https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip
unzip ${OPENCV_VERSION}.zip && rm ${OPENCV_VERSION}.zip
mv opencv-${OPENCV_VERSION} OpenCV
```
Then:

`cd OpenCV && mkdir build && cd build`

And so on.

I check and I didn't found an error.

Thanks for your comment.
