### ISSUE TITLE
Makefile:160: recipe for target 'all' failed make: *** [all] Error 2

### ISSUE THREAD

**Issue by jonathanrjpereira** [milq/milq#6]
**Ubuntu 16.10**

[ 13%] Generating precomp.hpp.gch/opencv_highgui_Release.gch
In file included from /usr/include/c++/6/bits/stl_algo.h:59:0,
                 from /usr/include/c++/6/algorithm:62,
                 from /home/jonathan/Desktop/OpenCV/modules/core/include/opencv2/core/base.hpp:55,
                 from /home/jonathan/Desktop/OpenCV/modules/core/include/opencv2/core.hpp:54,
                 from /home/jonathan/Desktop/OpenCV/modules/highgui/include/opencv2/highgui.hpp:46,
                 from /home/jonathan/Desktop/OpenCV/build/modules/highgui/precomp.hpp:45:
/usr/include/c++/6/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
modules/highgui/CMakeFiles/pch_Generate_opencv_highgui.dir/build.make:62: recipe for target 'modules/highgui/precomp.hpp.gch/opencv_highgui_Release.gch' failed
make[2]: *** [modules/highgui/precomp.hpp.gch/opencv_highgui_Release.gch] Error 1
CMakeFiles/Makefile2:4262: recipe for target 'modules/highgui/CMakeFiles/pch_Generate_opencv_highgui.dir/all' failed
make[1]: *** [modules/highgui/CMakeFiles/pch_Generate_opencv_highgui.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by avipars** [comment]
Try changing your cmake command to something like this: cmake -D CMAKE_BUILD_TYPE=RELEASE \
> -D CMAKE_INSTALL_PREFIX=/usr/local \
> -D INSTALL_PYTHON_EXAMPLES=ON \
> -D INSTALL_C_EXAMPLES=OFF \
> -D OPENCV_EXTRA_MODULES_PATH=~/opencv_contrib-3.1.0/modules \
> -D PYTHON_EXECUTABLE=~/.virtualenvs/cv/bin/python \
> -D BUILD_EXAMPLES=ON \
> -DENABLE_PRECOMPILED_HEADERS=OFF ..
